name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "PHPUNIT_API_EMAIL=${{ secrets.PHPUNIT_API_EMAIL }}" >> .env
          echo "PHPUNIT_API_PASSWORD=${{ secrets.PHPUNIT_API_PASSWORD }}" >> .env

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: php vendor/bin/phpunit
